// Code generated by protoc-gen-go.
// source: nats_msg.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	nats_msg.proto

It has these top-level messages:
	HnObjectRequest
	HnPost
	HnUser
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HnObjectRequestObjectType int32

const (
	HnObjectRequest_POST HnObjectRequestObjectType = 0
	HnObjectRequest_USER HnObjectRequestObjectType = 1
)

var HnObjectRequestObjectType_name = map[int32]string{
	0: "POST",
	1: "USER",
}
var HnObjectRequestObjectType_value = map[string]int32{
	"POST": 0,
	"USER": 1,
}

func (x HnObjectRequestObjectType) String() string {
	return proto.EnumName(HnObjectRequestObjectType_name, int32(x))
}
func (HnObjectRequestObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type HnObjectRequest struct {
	Id       int64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string                    `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Type     HnObjectRequestObjectType `protobuf:"varint,3,opt,name=type,enum=protocol.HnObjectRequestObjectType" json:"type,omitempty"`
}

func (m *HnObjectRequest) Reset()                    { *m = HnObjectRequest{} }
func (m *HnObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*HnObjectRequest) ProtoMessage()               {}
func (*HnObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HnObjectRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HnObjectRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *HnObjectRequest) GetType() HnObjectRequestObjectType {
	if m != nil {
		return m.Type
	}
	return HnObjectRequest_POST
}

type HnPost struct {
	Id          int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Deleted     bool    `protobuf:"varint,2,opt,name=deleted" json:"deleted,omitempty"`
	Type        string  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Author      string  `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	Time        int32   `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	Dead        bool    `protobuf:"varint,6,opt,name=dead" json:"dead,omitempty"`
	Parent      int64   `protobuf:"varint,7,opt,name=parent" json:"parent,omitempty"`
	Kids        []int64 `protobuf:"varint,8,rep,packed,name=kids" json:"kids,omitempty"`
	Url         string  `protobuf:"bytes,9,opt,name=url" json:"url,omitempty"`
	Title       string  `protobuf:"bytes,10,opt,name=title" json:"title,omitempty"`
	Parts       []int64 `protobuf:"varint,11,rep,packed,name=parts" json:"parts,omitempty"`
	Descendants int64   `protobuf:"varint,12,opt,name=descendants" json:"descendants,omitempty"`
	Text        string  `protobuf:"bytes,13,opt,name=text" json:"text,omitempty"`
	Source      int32   `protobuf:"varint,14,opt,name=source" json:"source,omitempty"`
	Score       int64   `protobuf:"varint,15,opt,name=score" json:"score,omitempty"`
}

func (m *HnPost) Reset()                    { *m = HnPost{} }
func (m *HnPost) String() string            { return proto.CompactTextString(m) }
func (*HnPost) ProtoMessage()               {}
func (*HnPost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HnPost) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HnPost) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *HnPost) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HnPost) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *HnPost) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *HnPost) GetDead() bool {
	if m != nil {
		return m.Dead
	}
	return false
}

func (m *HnPost) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *HnPost) GetKids() []int64 {
	if m != nil {
		return m.Kids
	}
	return nil
}

func (m *HnPost) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HnPost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HnPost) GetParts() []int64 {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *HnPost) GetDescendants() int64 {
	if m != nil {
		return m.Descendants
	}
	return 0
}

func (m *HnPost) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *HnPost) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *HnPost) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type HnUser struct {
	Id        string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Delay     int32   `protobuf:"varint,2,opt,name=delay" json:"delay,omitempty"`
	Created   int32   `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Karma     int64   `protobuf:"varint,4,opt,name=karma" json:"karma,omitempty"`
	About     string  `protobuf:"bytes,5,opt,name=about" json:"about,omitempty"`
	Submitted []int64 `protobuf:"varint,6,rep,packed,name=submitted" json:"submitted,omitempty"`
}

func (m *HnUser) Reset()                    { *m = HnUser{} }
func (m *HnUser) String() string            { return proto.CompactTextString(m) }
func (*HnUser) ProtoMessage()               {}
func (*HnUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HnUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HnUser) GetDelay() int32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *HnUser) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *HnUser) GetKarma() int64 {
	if m != nil {
		return m.Karma
	}
	return 0
}

func (m *HnUser) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *HnUser) GetSubmitted() []int64 {
	if m != nil {
		return m.Submitted
	}
	return nil
}

func init() {
	proto.RegisterType((*HnObjectRequest)(nil), "protocol.hn_object_request")
	proto.RegisterType((*HnPost)(nil), "protocol.hn_post")
	proto.RegisterType((*HnUser)(nil), "protocol.hn_user")
	proto.RegisterEnum("protocol.HnObjectRequestObjectType", HnObjectRequestObjectType_name, HnObjectRequestObjectType_value)
}

func init() { proto.RegisterFile("nats_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8e, 0xd3, 0x40,
	0x0c, 0x86, 0x49, 0xd3, 0xb4, 0x89, 0x0b, 0xa5, 0x8c, 0x56, 0xc8, 0x42, 0x1c, 0x42, 0x2f, 0xe4,
	0xd4, 0x03, 0x1c, 0x39, 0x73, 0x06, 0xcd, 0xc2, 0xb9, 0x9a, 0x66, 0x2c, 0x1a, 0x36, 0xc9, 0x84,
	0x19, 0x47, 0xda, 0x7d, 0x0e, 0x1e, 0x80, 0xa7, 0xe2, 0x7d, 0xd0, 0x38, 0x29, 0x54, 0x62, 0x4f,
	0xf5, 0xf7, 0xcb, 0x63, 0xff, 0xfe, 0x1b, 0xd8, 0xf6, 0x86, 0xc3, 0xb1, 0x0b, 0xdf, 0x0e, 0x83,
	0x77, 0xec, 0x54, 0x2e, 0x3f, 0xb5, 0x6b, 0xf7, 0xbf, 0x12, 0x78, 0x71, 0xee, 0x8f, 0xee, 0xf4,
	0x9d, 0x6a, 0x3e, 0x7a, 0xfa, 0x31, 0x52, 0x60, 0xb5, 0x85, 0x45, 0x63, 0x31, 0x29, 0x93, 0x2a,
	0xd5, 0x8b, 0xc6, 0xaa, 0x57, 0x90, 0x8f, 0x81, 0x7c, 0x6f, 0x3a, 0xc2, 0x45, 0x99, 0x54, 0x85,
	0xfe, 0xcb, 0xea, 0x03, 0x2c, 0xf9, 0x61, 0x20, 0x4c, 0xcb, 0xa4, 0xda, 0xbe, 0x7b, 0x7b, 0xb8,
	0x8c, 0x3e, 0xfc, 0x37, 0xf6, 0x30, 0x63, 0x6c, 0xd7, 0xf2, 0x68, 0xff, 0x06, 0x36, 0x57, 0xa2,
	0xca, 0x61, 0xf9, 0xf9, 0xd3, 0xed, 0x97, 0xdd, 0x93, 0x58, 0x7d, 0xbd, 0xfd, 0xa8, 0x77, 0xc9,
	0xfe, 0xf7, 0x02, 0xd6, 0xe7, 0xfe, 0x38, 0xb8, 0x47, 0x7c, 0x21, 0xac, 0x2d, 0xb5, 0xc4, 0x64,
	0xc5, 0x56, 0xae, 0x2f, 0xa8, 0xd4, 0x95, 0xab, 0x62, 0x5a, 0xa6, 0x5e, 0xc2, 0xca, 0x8c, 0x7c,
	0x76, 0x1e, 0x97, 0xa2, 0xce, 0x24, 0xbd, 0x4d, 0x47, 0x98, 0x95, 0x49, 0x95, 0x69, 0xa9, 0xa3,
	0x66, 0xc9, 0x58, 0x5c, 0xc9, 0x58, 0xa9, 0xe3, 0xfb, 0xc1, 0x78, 0xea, 0x19, 0xd7, 0xe2, 0x60,
	0xa6, 0xd8, 0x7b, 0xd7, 0xd8, 0x80, 0x79, 0x99, 0x56, 0xa9, 0x96, 0x5a, 0xed, 0x20, 0x1d, 0x7d,
	0x8b, 0x85, 0x2c, 0x8a, 0xa5, 0xba, 0x81, 0x8c, 0x1b, 0x6e, 0x09, 0x41, 0xb4, 0x09, 0xa2, 0x3a,
	0x18, 0xcf, 0x01, 0x37, 0xf2, 0x78, 0x02, 0x55, 0xc2, 0xc6, 0x52, 0xa8, 0xa9, 0xb7, 0xa6, 0xe7,
	0x80, 0x4f, 0x65, 0xdd, 0xb5, 0x24, 0x9e, 0xe9, 0x9e, 0xf1, 0xd9, 0x7c, 0x1f, 0xdd, 0x73, 0xf4,
	0x17, 0xdc, 0xe8, 0x6b, 0xc2, 0xad, 0x5c, 0x32, 0x53, 0xdc, 0x11, 0x6a, 0xe7, 0x09, 0x9f, 0xcb,
	0x9c, 0x09, 0xf6, 0x3f, 0x13, 0xc9, 0x35, 0xfe, 0x8f, 0x57, 0xb9, 0x16, 0x92, 0xeb, 0x0d, 0x64,
	0x96, 0x5a, 0xf3, 0x20, 0xa9, 0x66, 0x7a, 0x82, 0x98, 0x76, 0xed, 0xc9, 0xc4, 0xb4, 0x53, 0xd1,
	0x2f, 0x18, 0xfb, 0xef, 0x8c, 0xef, 0x8c, 0x04, 0x9b, 0xea, 0x09, 0xa2, 0x6a, 0x4e, 0x6e, 0x64,
	0x09, 0xb6, 0xd0, 0x13, 0xa8, 0xd7, 0x50, 0x84, 0xf1, 0xd4, 0x35, 0x1c, 0xe7, 0xac, 0xe4, 0xea,
	0x7f, 0xc2, 0x69, 0x25, 0x9f, 0xcf, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x82, 0xc4,
	0x77, 0xb2, 0x02, 0x00, 0x00,
}
