// Code generated by protoc-gen-gogo.
// source: nats_msg.proto
// DO NOT EDIT!

/*
	Package protocol is a generated protocol buffer package.

	It is generated from these files:
		nats_msg.proto

	It has these top-level messages:
		Post
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Post struct {
	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Deleted     bool    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Type        string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Author      string  `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Time        int64   `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Dead        bool    `protobuf:"varint,6,opt,name=dead,proto3" json:"dead,omitempty"`
	Parent      int64   `protobuf:"varint,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Kids        []int64 `protobuf:"varint,8,rep,packed,name=kids" json:"kids,omitempty"`
	Url         string  `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Title       string  `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Parts       []int64 `protobuf:"varint,11,rep,packed,name=parts" json:"parts,omitempty"`
	Descendants int64   `protobuf:"varint,12,opt,name=descendants,proto3" json:"descendants,omitempty"`
	Text        string  `protobuf:"bytes,13,opt,name=text,proto3" json:"text,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptorNatsMsg, []int{0} }

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Post) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Post) GetDead() bool {
	if m != nil {
		return m.Dead
	}
	return false
}

func (m *Post) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Post) GetKids() []int64 {
	if m != nil {
		return m.Kids
	}
	return nil
}

func (m *Post) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetParts() []int64 {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *Post) GetDescendants() int64 {
	if m != nil {
		return m.Descendants
	}
	return 0
}

func (m *Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "protocol.post")
}
func (m *Post) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Post) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(m.Id))
	}
	if m.Deleted {
		dAtA[i] = 0x10
		i++
		if m.Deleted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.Author) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(len(m.Author)))
		i += copy(dAtA[i:], m.Author)
	}
	if m.Time != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(m.Time))
	}
	if m.Dead {
		dAtA[i] = 0x30
		i++
		if m.Dead {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Parent != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(m.Parent))
	}
	if len(m.Kids) > 0 {
		dAtA2 := make([]byte, len(m.Kids)*10)
		var j1 int
		for _, num1 := range m.Kids {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x42
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.Url) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(len(m.Url)))
		i += copy(dAtA[i:], m.Url)
	}
	if len(m.Title) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(len(m.Title)))
		i += copy(dAtA[i:], m.Title)
	}
	if len(m.Parts) > 0 {
		dAtA4 := make([]byte, len(m.Parts)*10)
		var j3 int
		for _, num1 := range m.Parts {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x5a
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if m.Descendants != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(m.Descendants))
	}
	if len(m.Text) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintNatsMsg(dAtA, i, uint64(len(m.Text)))
		i += copy(dAtA[i:], m.Text)
	}
	return i, nil
}

func encodeFixed64NatsMsg(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32NatsMsg(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintNatsMsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Post) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovNatsMsg(uint64(m.Id))
	}
	if m.Deleted {
		n += 2
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovNatsMsg(uint64(l))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovNatsMsg(uint64(l))
	}
	if m.Time != 0 {
		n += 1 + sovNatsMsg(uint64(m.Time))
	}
	if m.Dead {
		n += 2
	}
	if m.Parent != 0 {
		n += 1 + sovNatsMsg(uint64(m.Parent))
	}
	if len(m.Kids) > 0 {
		l = 0
		for _, e := range m.Kids {
			l += sovNatsMsg(uint64(e))
		}
		n += 1 + sovNatsMsg(uint64(l)) + l
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovNatsMsg(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovNatsMsg(uint64(l))
	}
	if len(m.Parts) > 0 {
		l = 0
		for _, e := range m.Parts {
			l += sovNatsMsg(uint64(e))
		}
		n += 1 + sovNatsMsg(uint64(l)) + l
	}
	if m.Descendants != 0 {
		n += 1 + sovNatsMsg(uint64(m.Descendants))
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovNatsMsg(uint64(l))
	}
	return n
}

func sovNatsMsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozNatsMsg(x uint64) (n int) {
	return sovNatsMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Post) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNatsMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: post: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: post: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deleted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Deleted = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNatsMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNatsMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dead", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Dead = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			m.Parent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Parent |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowNatsMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Kids = append(m.Kids, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowNatsMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthNatsMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowNatsMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Kids = append(m.Kids, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Kids", wireType)
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNatsMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNatsMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowNatsMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Parts = append(m.Parts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowNatsMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthNatsMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowNatsMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Parts = append(m.Parts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Parts", wireType)
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Descendants", wireType)
			}
			m.Descendants = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Descendants |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNatsMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNatsMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNatsMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNatsMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNatsMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNatsMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthNatsMsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNatsMsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNatsMsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNatsMsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNatsMsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("nats_msg.proto", fileDescriptorNatsMsg) }

var fileDescriptorNatsMsg = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x71, 0xd2, 0xa6, 0xe9, 0x14, 0xaa, 0xca, 0x42, 0x68, 0x56, 0x51, 0xc4, 0x2a, 0x2b,
	0x36, 0xdc, 0x80, 0x23, 0xe4, 0x02, 0xc8, 0xd4, 0x23, 0xb0, 0x48, 0x63, 0xcb, 0x9e, 0x4a, 0xe5,
	0x26, 0x1c, 0x80, 0xc3, 0xb0, 0xe4, 0x08, 0x28, 0x5c, 0x04, 0x79, 0x1a, 0x24, 0x56, 0xfe, 0xff,
	0xe9, 0xff, 0x19, 0xdb, 0xb0, 0x1d, 0x0d, 0xa7, 0xc7, 0x43, 0x7a, 0xbe, 0x0b, 0xd1, 0xb3, 0xd7,
	0xb5, 0x1c, 0x7b, 0x3f, 0xdc, 0x7e, 0x14, 0xb0, 0x08, 0x3e, 0xb1, 0xde, 0x42, 0xe1, 0x2c, 0xaa,
	0x56, 0x75, 0x65, 0x5f, 0x38, 0xab, 0x11, 0x56, 0x96, 0x06, 0x62, 0xb2, 0x58, 0xb4, 0xaa, 0xab,
	0xfb, 0x3f, 0xab, 0x35, 0x2c, 0xf8, 0x2d, 0x10, 0x96, 0xad, 0xea, 0xd6, 0xbd, 0x68, 0x7d, 0x03,
	0x95, 0x39, 0xf2, 0x8b, 0x8f, 0xb8, 0x10, 0x3a, 0x3b, 0xc9, 0xba, 0x03, 0xe1, 0x52, 0xe6, 0x8a,
	0xce, 0xcc, 0x92, 0xb1, 0x58, 0xc9, 0x58, 0xd1, 0xb9, 0x1f, 0x4c, 0xa4, 0x91, 0x71, 0x25, 0xc9,
	0xd9, 0xe5, 0xec, 0xab, 0xb3, 0x09, 0xeb, 0xb6, 0xcc, 0xfd, 0xac, 0xf5, 0x0e, 0xca, 0x63, 0x1c,
	0x70, 0x2d, 0x8b, 0xb2, 0xd4, 0xd7, 0xb0, 0x64, 0xc7, 0x03, 0x21, 0x08, 0x3b, 0x9b, 0x4c, 0x83,
	0x89, 0x9c, 0x70, 0x23, 0xe5, 0xb3, 0xd1, 0x2d, 0x6c, 0x2c, 0xa5, 0x3d, 0x8d, 0xd6, 0x8c, 0x9c,
	0xf0, 0x52, 0xd6, 0xfd, 0x47, 0x72, 0x67, 0x3a, 0x31, 0x5e, 0xcd, 0xef, 0xa3, 0x13, 0x3f, 0xec,
	0x3e, 0xa7, 0x46, 0x7d, 0x4d, 0x8d, 0xfa, 0x9e, 0x1a, 0xf5, 0xfe, 0xd3, 0x5c, 0x3c, 0x55, 0xf2,
	0x85, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x21, 0xda, 0xe7, 0x5b, 0x01, 0x00, 0x00,
}
